# Generated by Django 3.1.1 on 2020-09-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, verbose_name="Document's Name")),
                ('document', models.FileField(upload_to='documents')),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
