# Generated by Django 3.1.1 on 2020-12-05 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_studentprofile_completed'),
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile'),
            preserve_default=False,
        ),
    ]
