# Generated by Django 3.1.1 on 2020-09-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
    ]
