# Generated by Django 3.1.1 on 2020-09-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='completed',
            field=models.CharField(choices=[('completed', 'completed'), ('incomplete', 'incomplete')], max_length=100, verbose_name='Status'),
        ),
    ]
