# Generated by Django 3.1.1 on 2020-12-02 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200917_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_school', models.CharField(max_length=255, verbose_name='Last School Attended')),
                ('strand', models.CharField(max_length=255, verbose_name='Strand')),
                ('last_school_year', models.CharField(max_length=255, verbose_name='Last School Year Attended')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile')),
            ],
        ),
    ]
