# Generated by Django 3.1.1 on 2020-12-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_previousschool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='completed',
        ),
    ]
